<a href="https://colab.research.google.com/github/BenFarz/demoX/blob/main/00_TensorFlow_output.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# This is my review of previous learning


In [22]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [4]:
ixix=tf.constant(7)
ixix

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
ixix.ndim

0

In [6]:
vector=tf.constant([4,3])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 3], dtype=int32)>

In [7]:
vector.ndim


1

In [8]:
mtx=tf.constant([[10,7],
                [7,10]])
mtx

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
mtx

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [10]:
mtx.ndim

2

In [11]:
mtx2=tf.constant([[1.,3.],
                  [34.,43.],
                  [2.,3.]], dtype=tf.float16)
mtx2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 1.,  3.],
       [34., 43.],
       [ 2.,  3.]], dtype=float16)>

In [12]:
mtx2.ndim

2

In [13]:
mtx3=tf.constant([[[3.,56.,76.],
                   [34.,43.,4.]],
                  [[2.,3.,4.],
                   [23.,32.,22.]],
                  [[28.,11.,22.],
                   [43.,56.,76.]]])
mtx3

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[ 3., 56., 76.],
        [34., 43.,  4.]],

       [[ 2.,  3.,  4.],
        [23., 32., 22.]],

       [[28., 11., 22.],
        [43., 56., 76.]]], dtype=float32)>

In [14]:
mtx3.ndim

3

# second trains of 'tf.variable'

In [35]:
changable=tf.Variable([11,7])
unchangable=tf.constant([11,7])
changable, unchangable 

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([11,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([11,  7], dtype=int32)>)

In [16]:
tia=tf.constant([12,221])
tia

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 12, 221], dtype=int32)>

In [17]:
changable[0].assign(9)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [18]:
rnd1=tf.random.Generator.from_seed(34)
rnd1=rnd1.normal(shape=(3,4))
rnd2=tf.random.Generator.from_seed(34)
rnd2=rnd2.normal(shape=(3,4))
rnd1, rnd2, rnd1==rnd2, rnd1[1]==rnd2[1]

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-1.5181769 ,  1.4020647 ,  1.5570306 , -0.96762174],
        [ 0.495291  , -0.648484  , -1.8700892 ,  2.7830641 ],
        [-0.645002  ,  0.18022095, -0.14656258,  0.34374258]],
       dtype=float32)>, <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-1.5181769 ,  1.4020647 ,  1.5570306 , -0.96762174],
        [ 0.495291  , -0.648484  , -1.8700892 ,  2.7830641 ],
        [-0.645002  ,  0.18022095, -0.14656258,  0.34374258]],
       dtype=float32)>, <tf.Tensor: shape=(3, 4), dtype=bool, numpy=
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])>, <tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True,  True,  True,  True])>)

In [19]:
rnd1[0]

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-1.5181769 ,  1.4020647 ,  1.5570306 , -0.96762174], dtype=float32)>

In [4]:
tobeshuffle=tf.constant([[1,2],
                        [34,7],
                        [5,78]])
tobeshuffle.ndim, tobeshuffle

(2, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 1,  2],
        [34,  7],
        [ 5, 78]], dtype=int32)>)

In [21]:
tf.random.shuffle(tobeshuffle)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5, 78],
       [34,  7],
       [ 1,  2]], dtype=int32)>

In [22]:
tf.random.set_seed(42)
we=tf.random.shuffle(tobeshuffle, seed=42)
tf.random.set_seed(43)
ve=tf.random.shuffle(tobeshuffle, seed=4)
we,ve

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 1,  2],
        [34,  7],
        [ 5, 78]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 1,  2],
        [34,  7],
        [ 5, 78]], dtype=int32)>)

In [23]:
new1=tf.constant([[1,2,3],
                 [23,2,3]])
new1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [23,  2,  3]], dtype=int32)>

In [24]:
new2=tf.random.Generator.from_seed(23)
new2=new2.uniform(shape=(5,6))
new2

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[0.9925091 , 0.20401764, 0.26398885, 0.79402816, 0.71974635,
        0.47845697],
       [0.21366036, 0.78412795, 0.93207085, 0.5625777 , 0.47580373,
        0.30543637],
       [0.5387846 , 0.06375635, 0.634938  , 0.6435729 , 0.3422103 ,
        0.8459996 ],
       [0.21559799, 0.10748649, 0.1337657 , 0.95617914, 0.6482675 ,
        0.55495536],
       [0.02367401, 0.74084485, 0.35598373, 0.29914415, 0.6900625 ,
        0.21108961]], dtype=float32)>

In [25]:
tf.random.set_seed(90)
new3=tf.random.shuffle(new2,seed=23)
new3

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[0.02367401, 0.74084485, 0.35598373, 0.29914415, 0.6900625 ,
        0.21108961],
       [0.5387846 , 0.06375635, 0.634938  , 0.6435729 , 0.3422103 ,
        0.8459996 ],
       [0.21366036, 0.78412795, 0.93207085, 0.5625777 , 0.47580373,
        0.30543637],
       [0.9925091 , 0.20401764, 0.26398885, 0.79402816, 0.71974635,
        0.47845697],
       [0.21559799, 0.10748649, 0.1337657 , 0.95617914, 0.6482675 ,
        0.55495536]], dtype=float32)>

In [26]:
tf.ones([4,5])


<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [27]:
tf.ones([3,4], tf.float16)

<tf.Tensor: shape=(3, 4), dtype=float16, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float16)>

In [28]:
tf.zeros(shape=(3,4))


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [5]:
import numpy as np

In [30]:
X=tf.constant([3,
               3])
X

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3], dtype=int32)>

In [31]:
numpy_A=np.arange(1,25, dtype=np.int16)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [32]:
A=tf.constant(numpy_A, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int16, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int16)>

In [34]:
b=np(A)
b

TypeError: ignored

In [ ]:
Tt=tf.constant([[1,1],
               [2,2]])
Tt.ndim
tf.size(Tt)

In [ ]:
Rank4_dim=tf.zeros([2,3,4,5])
Rank4_dim

In [ ]:
Rank4_dim[0]

In [ ]:
Rank4_dim[1]

In [ ]:
Rank4_dim.ndim

In [ ]:
#Rank4_dim[0],
#Rank4_dim[1],
#Rank4_dim[2],
Rank4_dim[1,1,1,4]


In [ ]:
tf.size(Rank4_dim),tf.shape(Rank4_dim)

In [ ]:
Rank4_dim.shape

In [ ]:
tf.shape(Rank4_dim)

In [ ]:
tf.size(Rank4_dim)

In [38]:
Txx=tf.constant([[[1,2,3,4],
               [44,55,66,77],
               [11,22,33,44]],
               [[-11,-11,-22,0],
                [-33,-22,-45,1],
                [-90,-33,-5,2]]])
Txx

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[  1,   2,   3,   4],
        [ 44,  55,  66,  77],
        [ 11,  22,  33,  44]],

       [[-11, -11, -22,   0],
        [-33, -22, -45,   1],
        [-90, -33,  -5,   2]]], dtype=int32)>

In [42]:
Txx[0,1:3,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([77, 44], dtype=int32)>

In [40]:
print("data type of every elemt", Txx.dtype)
print("Rank of the Txx", Txx.ndim)
print("shape of Tensor", Txx.shape)
print("elemnt along the zero axix", Txx.shape[0])
print("elemnt along the last axis", Txx.shape[-1])
print("Total number of elemnt in out tensor", tf.size(Txx))
print("Total number of elemnt in out tensor", tf.size(Txx).numpy())

data type of every elemt <dtype: 'int32'>
Rank of the Txx 3
shape of Tensor (2, 3, 4)
elemnt along the zero axix 2
elemnt along the last axis 4
Total number of elemnt in out tensor tf.Tensor(24, shape=(), dtype=int32)
Total number of elemnt in out tensor 24


In [71]:
Txx[:,1:3,-1]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[77, 44],
       [ 1,  2]], dtype=int32)>

In [8]:
Rk2=tf.constant([[10,7],
                 [34,3]])
Rk2.shape, Rk2.ndim, Rk2[:,1:2]

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[7],
        [3]], dtype=int32)>)

In [54]:
Rk3=Rk2[...,tf.newaxis]
Rk3, Rk3.shape

(<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[34],
         [ 3]]], dtype=int32)>, TensorShape([2, 2, 1]))

In [23]:
Rk2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [34,  3]], dtype=int32)>

In [56]:
Rk4=Rk2[:,tf.newaxis]
Rk4

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[34,  3]]], dtype=int32)>

In [58]:
Rk5=tf.expand_dims(Rk2, axis=1)
Rk5

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[34,  3]]], dtype=int32)>

In [9]:
tf.multiply(Rk2,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [340,  30]], dtype=int32)>

In [13]:

tf.matmul(Rk2,Rk2), Rk2


(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[338,  91],
        [442, 247]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [34,  3]], dtype=int32)>)

In [14]:
Rk2@Rk2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[338,  91],
       [442, 247]], dtype=int32)>

In [19]:
Rk32=tf.constant([[2,3],
                 [6,7],
                  [4,5]])
tf.reshape(Rk32, shape=(2,3)), Rk32, Rk2@tf.reshape(Rk32, shape=(2,3))


(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[2, 3, 6],
        [7, 4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 3],
        [6, 7],
        [4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 69,  58,  95],
        [ 89, 114, 219]], dtype=int32)>)

In [20]:
tf.transpose(Rk32)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 6, 4],
       [3, 7, 5]], dtype=int32)>

In [21]:
Rk2@tf.transpose(Rk32)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 41, 109,  75],
       [ 77, 225, 151]], dtype=int32)>

In [29]:
print(tf.reshape(Rk2, shape=(1,4)))
print(tf.reshape(Rk2, shape=(1,4)))

tf.Tensor([[10  7 34  3]], shape=(1, 4), dtype=int32)
tf.Tensor([[10  7 34  3]], shape=(1, 4), dtype=int32)


In [31]:
Rk2=tf.cast(Rk2, dtype=tf.bfloat16)
Rk2

<tf.Tensor: shape=(2, 2), dtype=bfloat16, numpy=
array([[10, 7],
       [34, 3]], dtype=bfloat16)>