<a href="https://colab.research.google.com/github/BenFarz/demoX/blob/main/00_TensorFlow_output.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# This is my review of previous learning


In [1]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [2]:
ixix=tf.constant(7)
ixix

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
ixix.ndim

0

In [5]:
vector=tf.constant([4,3])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 3], dtype=int32)>

In [6]:
vector.ndim


1

In [7]:
mtx=tf.constant([[10,7],
                [7,10]])
mtx

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
mtx

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
mtx.ndim

2

In [10]:
mtx2=tf.constant([[1.,3.],
                  [34.,43.],
                  [2.,3.]], dtype=tf.float16)
mtx2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 1.,  3.],
       [34., 43.],
       [ 2.,  3.]], dtype=float16)>

In [11]:
mtx2.ndim

2

In [12]:
mtx3=tf.constant([[[3.,56.,76.],
                   [34.,43.,4.]],
                  [[2.,3.,4.],
                   [23.,32.,22.]],
                  [[28.,11.,22.],
                   [43.,56.,76.]]])
mtx3

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[ 3., 56., 76.],
        [34., 43.,  4.]],

       [[ 2.,  3.,  4.],
        [23., 32., 22.]],

       [[28., 11., 22.],
        [43., 56., 76.]]], dtype=float32)>

In [13]:
mtx3.ndim

3

# second trains of 'tf.variable'

In [14]:
changable=tf.Variable([11,7])
unchangable=tf.constant([11,7])
changable, unchangable 

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([11,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([11,  7], dtype=int32)>)

In [15]:
tia=tf.constant([12,221])
tia

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 12, 221], dtype=int32)>

In [16]:
changable[0].assign(9)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [17]:
rnd1=tf.random.Generator.from_seed(34)
rnd1=rnd1.normal(shape=(3,4))
rnd2=tf.random.Generator.from_seed(34)
rnd2=rnd2.normal(shape=(3,4))
rnd1, rnd2, rnd1==rnd2, rnd1[1]==rnd2[1]

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-1.5181769 ,  1.4020647 ,  1.5570306 , -0.96762174],
        [ 0.495291  , -0.648484  , -1.8700892 ,  2.7830641 ],
        [-0.645002  ,  0.18022095, -0.14656258,  0.34374258]],
       dtype=float32)>, <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-1.5181769 ,  1.4020647 ,  1.5570306 , -0.96762174],
        [ 0.495291  , -0.648484  , -1.8700892 ,  2.7830641 ],
        [-0.645002  ,  0.18022095, -0.14656258,  0.34374258]],
       dtype=float32)>, <tf.Tensor: shape=(3, 4), dtype=bool, numpy=
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])>, <tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True,  True,  True,  True])>)

In [18]:
rnd1[0]

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-1.5181769 ,  1.4020647 ,  1.5570306 , -0.96762174], dtype=float32)>

In [19]:
tobeshuffle=tf.constant([[1,2],
                        [34,7],
                        [5,78]])
tobeshuffle.ndim, tobeshuffle

(2, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 1,  2],
        [34,  7],
        [ 5, 78]], dtype=int32)>)

In [20]:
tf.random.shuffle(tobeshuffle)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  2],
       [34,  7],
       [ 5, 78]], dtype=int32)>

In [21]:
tf.random.set_seed(42)
we=tf.random.shuffle(tobeshuffle, seed=42)
tf.random.set_seed(43)
ve=tf.random.shuffle(tobeshuffle, seed=4)
we,ve

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 1,  2],
        [34,  7],
        [ 5, 78]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 1,  2],
        [34,  7],
        [ 5, 78]], dtype=int32)>)

In [22]:
new1=tf.constant([[1,2,3],
                 [23,2,3]])
new1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [23,  2,  3]], dtype=int32)>

In [23]:
new2=tf.random.Generator.from_seed(23)
new2=new2.uniform(shape=(5,6))
new2

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[0.9925091 , 0.20401764, 0.26398885, 0.79402816, 0.71974635,
        0.47845697],
       [0.21366036, 0.78412795, 0.93207085, 0.5625777 , 0.47580373,
        0.30543637],
       [0.5387846 , 0.06375635, 0.634938  , 0.6435729 , 0.3422103 ,
        0.8459996 ],
       [0.21559799, 0.10748649, 0.1337657 , 0.95617914, 0.6482675 ,
        0.55495536],
       [0.02367401, 0.74084485, 0.35598373, 0.29914415, 0.6900625 ,
        0.21108961]], dtype=float32)>

In [24]:

tf.random.set_seed(90)
new3=tf.random.shuffle(new2,seed=23)
new3

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[0.02367401, 0.74084485, 0.35598373, 0.29914415, 0.6900625 ,
        0.21108961],
       [0.5387846 , 0.06375635, 0.634938  , 0.6435729 , 0.3422103 ,
        0.8459996 ],
       [0.21366036, 0.78412795, 0.93207085, 0.5625777 , 0.47580373,
        0.30543637],
       [0.9925091 , 0.20401764, 0.26398885, 0.79402816, 0.71974635,
        0.47845697],
       [0.21559799, 0.10748649, 0.1337657 , 0.95617914, 0.6482675 ,
        0.55495536]], dtype=float32)>

In [25]:
tf.ones([4,5])


<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [26]:
tf.ones([3,4], tf.float16)

<tf.Tensor: shape=(3, 4), dtype=float16, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float16)>

In [27]:
tf.zeros(shape=(3,4))


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [3]:
import numpy as np

In [29]:
X=tf.constant([3,
               3])
X

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3], dtype=int32)>

In [30]:
numpy_A=np.arange(1,25, dtype=np.int16)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [31]:
A=tf.constant(numpy_A, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int16, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int16)>

In [35]:
#Rank4_dim[0],
#Rank4_dim[1],
#Rank4_dim[2],
Rank4_dim[1,1,1,4]


NameError: ignored

In [36]:
tf.size(Rank4_dim),tf.shape(Rank4_dim)

NameError: ignored

In [37]:
Rank4_dim.shape

NameError: ignored

In [38]:
tf.shape(Rank4_dim)

NameError: ignored

In [39]:
tf.size(Rank4_dim)

NameError: ignored

In [40]:
Txx=tf.constant([[[1,2,3,4],
               [44,55,66,77],
               [11,22,33,44]],
               [[-11,-11,-22,0],
                [-33,-22,-45,1],
                [-90,-33,-5,2]]])
Txx

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[  1,   2,   3,   4],
        [ 44,  55,  66,  77],
        [ 11,  22,  33,  44]],

       [[-11, -11, -22,   0],
        [-33, -22, -45,   1],
        [-90, -33,  -5,   2]]], dtype=int32)>

In [41]:
Txx[0,1:3,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([77, 44], dtype=int32)>

In [42]:
print("data type of every elemt", Txx.dtype)
print("Rank of the Txx", Txx.ndim)
print("shape of Tensor", Txx.shape)
print("elemnt along the zero axix", Txx.shape[0])
print("elemnt along the last axis", Txx.shape[-1])
print("Total number of elemnt in out tensor", tf.size(Txx))
print("Total number of elemnt in out tensor", tf.size(Txx).numpy())

data type of every elemt <dtype: 'int32'>
Rank of the Txx 3
shape of Tensor (2, 3, 4)
elemnt along the zero axix 2
elemnt along the last axis 4
Total number of elemnt in out tensor tf.Tensor(24, shape=(), dtype=int32)
Total number of elemnt in out tensor 24


### FIND positional Mximum and minimum

In [4]:
tf.random.set_seed(54)
f=tf.random.uniform(shape=[50], seed=44)
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.3716128 , 0.44222832, 0.5605713 , 0.8743068 , 0.17082143,
       0.46452737, 0.52323043, 0.20964503, 0.10697722, 0.03946435,
       0.87404966, 0.71768963, 0.10574532, 0.35310626, 0.76714325,
       0.56622696, 0.6238972 , 0.1610552 , 0.7993288 , 0.5770093 ,
       0.36919117, 0.76673937, 0.10263765, 0.5047549 , 0.3360616 ,
       0.07203269, 0.8152616 , 0.52208686, 0.20519626, 0.15474212,
       0.886305  , 0.8356123 , 0.454759  , 0.07868052, 0.28148925,
       0.50434506, 0.8965223 , 0.30998552, 0.34294426, 0.34674597,
       0.41932583, 0.14564085, 0.9628029 , 0.7540554 , 0.01785898,
       0.10919309, 0.7209574 , 0.2311883 , 0.11368942, 0.17573357],
      dtype=float32)>

In [44]:
tf.argmax(f), f[tf.argmax(f)], tf.reduce_max(f)

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9628029>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9628029>)

In [45]:
assert f[tf.argmax(f)]==tf.reduce_max(f)

In [6]:
Tg=tf.constant(np.random.randint(0,100,100), shape=[2,5,10])

Tg

<tf.Tensor: shape=(2, 5, 10), dtype=int64, numpy=
array([[[95, 13, 85, 25, 56, 21, 30, 29,  9, 13],
        [76, 96, 25, 23, 84, 53, 68, 81, 54, 87],
        [35, 56, 77, 25,  6, 21, 62, 83, 51,  2],
        [77, 87, 63, 82, 79, 65, 73,  2, 59,  1],
        [ 8, 50, 26, 39, 98, 82, 28,  6, 58, 73]],

       [[59, 95, 77, 16, 99, 21, 89, 40, 80, 20],
        [65, 58, 37, 63, 76, 91, 35, 69, 60, 75],
        [54, 79, 90, 24, 38, 93, 38, 37, 45, 29],
        [74, 82, 23, 61, 23,  7, 61, 94, 63, 82],
        [42, 45, 50, 25, 72, 66, 54, 21, 95, 44]]])>

In [47]:
tf.reduce_max(Tg)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [7]:
tf.argmax(Tg)
#Tg[tf.argmax(Tg)]


<tf.Tensor: shape=(5, 10), dtype=int64, numpy=
array([[0, 1, 0, 0, 1, 0, 1, 1, 1, 1],
       [0, 0, 1, 1, 0, 1, 0, 0, 1, 0],
       [1, 1, 1, 0, 1, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [1, 0, 1, 0, 0, 0, 1, 1, 1, 0]])>

In [49]:
gt=tf.reshape(Tg,[1,100])
gt

<tf.Tensor: shape=(1, 100), dtype=int64, numpy=
array([[76,  2, 71, 56, 88, 13, 19, 53, 37,  9, 53, 94, 63, 52, 33, 38,
        13, 83,  0, 23, 14, 72,  2, 68, 56, 79, 46, 70, 10, 53, 10, 37,
         2, 26, 18, 15, 42, 41, 86, 90, 35, 14, 81, 41, 29,  4, 46, 46,
         5, 42, 26, 17, 36, 57, 28, 86, 88, 51, 98, 88, 79, 22, 61, 22,
        45, 71, 16, 85, 94, 14, 55, 46, 21, 87, 80, 89, 31, 84, 64, 52,
        16, 31, 66, 34, 26, 19, 76, 78, 62, 64, 28, 59, 44, 63, 58, 83,
         6, 55, 92, 95]])>

In [50]:
gt100=gt/100
gt100

<tf.Tensor: shape=(1, 100), dtype=float64, numpy=
array([[0.76, 0.02, 0.71, 0.56, 0.88, 0.13, 0.19, 0.53, 0.37, 0.09, 0.53,
        0.94, 0.63, 0.52, 0.33, 0.38, 0.13, 0.83, 0.  , 0.23, 0.14, 0.72,
        0.02, 0.68, 0.56, 0.79, 0.46, 0.7 , 0.1 , 0.53, 0.1 , 0.37, 0.02,
        0.26, 0.18, 0.15, 0.42, 0.41, 0.86, 0.9 , 0.35, 0.14, 0.81, 0.41,
        0.29, 0.04, 0.46, 0.46, 0.05, 0.42, 0.26, 0.17, 0.36, 0.57, 0.28,
        0.86, 0.88, 0.51, 0.98, 0.88, 0.79, 0.22, 0.61, 0.22, 0.45, 0.71,
        0.16, 0.85, 0.94, 0.14, 0.55, 0.46, 0.21, 0.87, 0.8 , 0.89, 0.31,
        0.84, 0.64, 0.52, 0.16, 0.31, 0.66, 0.34, 0.26, 0.19, 0.76, 0.78,
        0.62, 0.64, 0.28, 0.59, 0.44, 0.63, 0.58, 0.83, 0.06, 0.55, 0.92,
        0.95]])>

In [51]:
tf.argmax(gt100)

<tf.Tensor: shape=(100,), dtype=int64, numpy=
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])>

In [52]:
yu = tf.constant([10,70,444,5,4,3])
tf.argmax(yu), yu[tf.argmax(yu)]
               

(<tf.Tensor: shape=(), dtype=int64, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=444>)

In [59]:
GG=tf.squeeze(gt)
GG,GG.shape,gt.shape

(<tf.Tensor: shape=(100,), dtype=int64, numpy=
 array([76,  2, 71, 56, 88, 13, 19, 53, 37,  9, 53, 94, 63, 52, 33, 38, 13,
        83,  0, 23, 14, 72,  2, 68, 56, 79, 46, 70, 10, 53, 10, 37,  2, 26,
        18, 15, 42, 41, 86, 90, 35, 14, 81, 41, 29,  4, 46, 46,  5, 42, 26,
        17, 36, 57, 28, 86, 88, 51, 98, 88, 79, 22, 61, 22, 45, 71, 16, 85,
        94, 14, 55, 46, 21, 87, 80, 89, 31, 84, 64, 52, 16, 31, 66, 34, 26,
        19, 76, 78, 62, 64, 28, 59, 44, 63, 58, 83,  6, 55, 92, 95])>,
 TensorShape([100]),
 TensorShape([1, 100]))

In [61]:
GG[tf.argmax(GG)],tf.argmax(GG)


(<tf.Tensor: shape=(), dtype=int64, numpy=98>,
 <tf.Tensor: shape=(), dtype=int64, numpy=58>)

In [53]:
tf.reduce_max(Tg)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [10]:
sl=[0,1,2,3]
sl

[0, 1, 2, 3]

In [11]:
tf.one_hot(sl,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [12]:
tf.one_hot(sl, depth=3, on_value="->", off_value="O")

<tf.Tensor: shape=(4, 3), dtype=string, numpy=
array([[b'->', b'O', b'O'],
       [b'O', b'->', b'O'],
       [b'O', b'O', b'->'],
       [b'O', b'O', b'O']], dtype=object)>

In [14]:
GG=tf.range(1,10,2)
GG

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

In [19]:
tf.square(tf.cast(GG, dtype=tf.float32))

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 1.,  9., 25., 49., 81.], dtype=float32)>

In [24]:
gg=tf.sqrt(tf.cast(GG, dtype=tf.float32))
gg

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([1.       , 1.7320508, 2.236068 , 2.6457512, 3.       ],
      dtype=float32)>

In [25]:
tf.constant([56,7])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([56,  7], dtype=int32)>

In [29]:
PH=tf.constant(np.array([6,7,9]))
PH,type(PH)

(<tf.Tensor: shape=(3,), dtype=int64, numpy=array([6, 7, 9])>,
 tensorflow.python.framework.ops.EagerTensor)

In [37]:
ZA=tf.constant([[3,4,5],
                [4,5,4]])
za=np.array(ZA)
zaa=tf.squeeze(za)
print(ZA, type(ZA), "\n")
print(za,type(za), "\n")
print(zaa, type(zaa))

tf.Tensor(
[[3 4 5]
 [4 5 4]], shape=(2, 3), dtype=int32) <class 'tensorflow.python.framework.ops.EagerTensor'> 

[[3 4 5]
 [4 5 4]] <class 'numpy.ndarray'> 

tf.Tensor(
[[3 4 5]
 [4 5 4]], shape=(2, 3), dtype=int32) <class 'tensorflow.python.framework.ops.EagerTensor'>


In [42]:
xxx=np.array(tf.squeeze(tf.reshape(ZA, [1,6])))
yyy=xxx=np.array(tf.reshape(ZA, [6]))
xxx,yyy

(array([3, 4, 5, 4, 5, 4], dtype=int32),
 array([3, 4, 5, 4, 5, 4], dtype=int32))